# Generated by Django 4.1.3 on 2022-11-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolourmodel',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Colours', to='Productapi.productmainmodel'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='Productapi.productmainmodel'),
        ),
    ]
